// File: lib/firebase_options.dart
// This file is auto-generated by the FlutterFire CLI.
// If you haven't run 'flutterfire configure', you should do so to generate the correct keys for your project.
// Below is a structure based on your screenshot 894.jpg.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these values with the actual keys from your Firebase Console or Screenshot 894.jpg
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdVUbDAlmFS70s2u_4zhhfZ3m7ildaNaw', 
    appId: '1:497549212515:android:87d6dbfde7af580f4bf156',
    messagingSenderId: '497549212515',
    projectId: 'todolist-37833',
    authDomain: 'todolist-37833.firebaseapp.com',
    storageBucket: 'todolist-37833.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdVUbDAlmFS70s2u_4zhhfZ3m7ildaNaw',
    appId: '1:497549212515:android:87d6dbfde7af580f4bf156',
    messagingSenderId: '497549212515',
    projectId: 'todolist-37833',
    storageBucket: 'todolist-37833.appspot.com',
  );
}